use HireWheels;
select * from booking;
desc booking;

insert into booking values
(3,'2020-05-25',' 2020-05-26', '2020-05-25', 2000 , 1, 4,  1 ),
(4 ,'2020-05-25', '2020-05-26', '2020-05-25', 1000 , 2, 2,  2 ),
(5,'2020-05-25', '2020-05-26', '2020-05-25', 1000 , 1, 4,  1 ),
(6, '2020-05-25', '2020-05-26', '2020-05-25', 1000 , 2, 1,  3 );

-- todo 1
select vehical_id, count(vehical_id) as 'Number of bookings'
from booking where booking_date = '2020-05-25'
group by vehical_id
order by count(vehical_id) desc ; 
-- todo 2
select  vehical_id, sum(amount) as 'Revenue'
from booking  group by vehical_id order by sum(amount) desc;
-- todo 3
select user_id as ID from user 
where user_id not in (select user_id from booking);

/**
TODO 1: Find the number of times a vehicle was booked on 25 May 2020 and display them
in descending order of their number of bookings.

The query should return the following columns: 
	Vehicle_id
	Total number of times the vehicle was booked on 25 May 2020 as “Number of Bookings” 
**/

/**
TODO 2: Find the revenue generated by each vehicle, and display them in descending order of
their revenue. List only those vehicles that have had any bookings.

The returned table should contain the following two columns:
	Vehicle_id
	Amount generated by that particular vehicle as “Revenue”
**/

/**
TODO 3: Make a list of unique IDs of all the users who have not booked any vehicle so far.

The result should only contain the user_id displayed as ‘ID’. 
**/
